dist: focal

language: cpp

compiler:
  - gcc

before_script:
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install cmake
  - sudo apt-get -y install curl
  - sudo apt-get -y install libssl-dev
  - sudo apt-get -y install doxygen
  - sudo apt-get -y install libclang1-9
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - sudo cmake .. -DGMX_BUILD_OWN_FFTW=ON 

script:
  # once CMake has done its job we just build using make as usual
  #- make
  # if the project uses ctest we can run the tests like this
  # - make test
  - sudo make 
  - sudo make install
  - sudo source /usr/local/gromacs/bin/GMXRC